### ISSUE TITLE
FIFO - Period stripped from name variable

### ISSUE THREAD

**Issue by klesher** [cloudposse/terraform-aws-sns-topic#40]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
When specifying a topic `name` variable ending in `.fifo`, the period is stripped.  This `.fifo` suffix is required by AWS when naming FIFO queues.

## Expected Behavior
.fifo to remain in place as this is required for FIFO queues by AWS.

## Steps to Reproduce
Create a new queue with name ending in `.fifo`.

Ex:
Setting it to `-fifo` leaves it unchanged:
 `results-test-fifo`

But ending in `.fifo` strips the period:
`results-testfifo`

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
Tested with `terraform-aws-sns-topic` module versions 19.2 and 17.0 (when this feature was released).

## Additional Context
Digging through the module, I see there’s a `replace(module.this.id, ".", "-")` for [display_name](https://github.com/cloudposse/terraform-aws-sns-topic/blob/c61835f686855245e7f4af264a16d2874a67e5d5/main.tf#L13), but I’m not seeing why it’s happening for the Topic name.

I was able to work around this by setting the `delimiter` and `attributes` values, however this seems like it's not an intended use:

```
name = "results-test"
delimiter = "."
attributes = ["fifo"]
```
Results in:
`results-test.fifo`

**Comment by nitrocode** [comment]
This is a bug. Good find. The reason the period is stripped is due to `regex_replace_chars` from the `context.tf` which defaults to `"/[^a-zA-Z0-9-]/"` unless overwritten.

For now, you should be able to set this and the period will not be stripped.

```hcl
  regex_replace_chars = "/[^a-zA-Z0-9-.]/"
```

**Comment by nitrocode** [comment]
@klesher can you try using this branch and see if it works as expected ?

```hcl
module "sns" {
  source = "git::https://github.com/cloudposse/terraform-aws-sns-topic.git?ref=sqs_queue_allow_periods"
  # ...
}
```

**Comment by klesher** [comment]
Hi Nitrocode!  Looks like that did the trick!  I'm able to remove the `delimiter` and `attributes` values I have set now.

The only minor issue (?) I see at this point is that the "Name" tag doesn't have `.fifo` appended to it.  The `Name` tag is often what AWS uses for ordering in the console, so I try to keep this matching the actual name of a resource where possible.  I can work around this if I'm wrong in my assumption, so not a big deal!

```
  tags = merge({
    terraform-managed = true
    project           = var.project
    environment       = var.environment
    Name              = local.name      <----
  }, var.tags)
```


```
  ~ resource "aws_sns_topic" "this" {
      ...
      ~ tags                        = {
          - "Attributes"        = "fifo" -> null
          ~ "Name"              = "results-test.fifo" -> "results-test"
            # (3 unchanged elements hidden)
        }
      ~ tags_all                    = {
          - "Attributes"        = "fifo" -> null
          ~ "Name"              = "results-test.fifo" -> "results-test"
            # (3 unchanged elements hidden)
        }
        # (6 unchanged attributes hidden)
    }
```

**Comment by nitrocode** [comment]
@klesher I updated it and it should be updating the `Name` tag correctly on the sns topic and queue. Please try it again when you get a chance.

**Comment by klesher** [comment]
Hey @nitrocode - just tested this out and it's working as I'd expect!

Thank you for working on this, much appreciated!

**Comment by nitrocode** [comment]
@klesher this has been fixed as part of https://github.com/cloudposse/terraform-aws-sns-topic/releases/tag/0.20.0

Thanks again for submitting this!
