### ISSUE TITLE
Support SQS Dead Letter Queue's redrive_policy

### ISSUE THREAD

**Issue by latacora-tomekr** [cloudposse/terraform-aws-sns-topic#42]
## Describe the Feature

The README states:

> It's possible to subscribe SQS as Dead Letter Queue. Unfortunately redrive_policy is not yet available in terraform. It's waiting for PR https://github.com/terraform-providers/terraform-provider-aws/pull/11770 Without redrive_policy it's impossible to configure DLQ.

However, https://github.com/terraform-providers/terraform-provider-aws/pull/11770 was merged on Feb 6 so should be available now.

## References
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue#redrive_policy

**Comment by nitrocode** [comment]
@latacora-tomekr have you tried the option `sqs_dlq_enabled = true` ?

**Comment by nitrocode** [comment]
This has been fixed as of https://github.com/cloudposse/terraform-aws-sns-topic/releases/tag/0.20.0. Thanks for creating this issue.

**Comment by nathan-mikkelsen** [comment]
Why was sns updated to 0.20.0 to fix this issue when the original poster asked about sqs? As of now I'm unable to get the redrive policy on sqs module to work.
