### ISSUE TITLE
Enable encryption in resource aws_sns_topic

### ISSUE THREAD

**Issue by razorsedge** [cloudposse/terraform-aws-sns-topic#7]
## Describe the Feature

Enable togglable encryption in resource `aws_sns_topic`.

## Expected Behavior

Encryption should be enabled upon creation of the SNS topic.  A variable should allow for disabling encryption.

## Use Case

Because, ENCRYPTION.

**Comment by 3h4x** [comment]
Thank @razorsedge .
That sounds like great feature. Currently I don't have enough time to update this repository.
We welcome PRs from community though!
